apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-deployment
  labels:
    app: pythonfastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonfastapi
  template: 
    metadata:
      labels:
        app: pythonfastapi
    spec:
      containers:
      - name: pythonfastapi
        image: tjhirani/pythonfastapi:latest
        ports:
        - containerPort: 5000
